import type { Metadata } from 'next';

export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://bursar.world';

/** The share card for a path: `/` is `home`, `/blog/a-post` is `blog-a-post`. Generated by scripts/og.mjs. */
export function ogImage(path: string) {
  return `/og/${path === '/' ? 'home' : path.slice(1).replaceAll('/', '-')}.jpg`;
}

/**
 * Per-page head tags. Next replaces the layout's `openGraph` and `twitter` objects wholesale
 * rather than merging them, so every page restates the site-wide fields alongside its own.
 * `path` resolves against the layout's `metadataBase` into the canonical URL and `og:url`.
 */
export function pageMetadata({
  title,
  description,
  ogDescription = description,
  path,
  article,
}: {
  readonly title: string;
  readonly description: string;
  readonly ogDescription?: string;
  readonly path: string;
  readonly article?: { readonly published: string; readonly modified: string; readonly section: string };
}): Metadata {
  const image = { url: ogImage(path), width: 1200, height: 630, alt: title };
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      title,
      description: ogDescription,
      url: path,
      siteName: 'Bursar',
      locale: 'en_US',
      images: [image],
      ...(article
        ? {
            type: 'article',
            publishedTime: article.published,
            modifiedTime: article.modified,
            section: article.section,
            authors: [`${SITE_URL}/about`],
          }
        : { type: 'website' }),
    },
    twitter: {
      card: 'summary_large_image',
      site: '@UseBursar',
      title,
      description: ogDescription,
      images: [image],
    },
  };
}
