/* eslint-disable @next/next/no-img-element -- the export is static, so images are pre-generated by scripts/images.mjs */
import type { CSSProperties } from 'react';

import { IMAGES, type ImageKey, type ImageSet } from '../_images';

const srcSet = (set: ImageSet) => set.map(([src, width]) => `${src} ${width}w`).join(', ');

/**
 * A responsive image: AVIF and WebP sources with a JPEG fallback, all at several widths. The
 * `picture` element is `display: contents` in the stylesheet, so the `img` lays out exactly as
 * it would without the wrapper.
 *
 * `width` and `height` carry the source's natural size, which reserves the right box before the
 * file arrives. Where the stylesheet fixes only the height and lets the width follow the image,
 * pass `ratioOnly`: the attributes would pin the width, so the ratio is given in CSS instead.
 *
 * `priority` is for the image that paints the largest element on first load: it is fetched
 * eagerly and first. `eager` is for other images in the first viewport; everything else loads lazily.
 */
export function Picture({
  image,
  alt,
  sizes,
  className,
  priority = false,
  eager = false,
  ratioOnly = false,
}: {
  readonly image: ImageKey;
  readonly alt: string;
  readonly sizes: string;
  readonly className?: string;
  readonly priority?: boolean;
  readonly eager?: boolean;
  readonly ratioOnly?: boolean;
}) {
  const entry = IMAGES[image];
  const fallback = entry.jpg[entry.jpg.length - 1]![0];
  const style: CSSProperties | undefined = ratioOnly ? { aspectRatio: `${entry.width} / ${entry.height}` } : undefined;
  return (
    <picture>
      <source type="image/avif" srcSet={srcSet(entry.avif)} sizes={sizes} />
      <source type="image/webp" srcSet={srcSet(entry.webp)} sizes={sizes} />
      <img
        className={className}
        src={fallback}
        srcSet={srcSet(entry.jpg)}
        sizes={sizes}
        alt={alt}
        width={ratioOnly ? undefined : entry.width}
        height={ratioOnly ? undefined : entry.height}
        style={style}
        loading={priority || eager ? 'eager' : 'lazy'}
        decoding={priority ? undefined : 'async'}
        fetchPriority={priority ? 'high' : undefined}
      />
    </picture>
  );
}
