// Pre-generates every raster the site serves: AVIF, WebP and a JPEG fallback for each source image
// at a ladder of widths, plus the favicon and app icon set. The site is a static export, so nothing
// is resized at request time. Output file names carry a content hash, which lets the host cache
// /img/ for a year. Run with `pnpm images` after changing anything in public/brand or public/stock;
// it rewrites public/img, public/icons and src/app/_images.ts.
import { createHash } from 'node:crypto';
import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import sharp from 'sharp';

const ROOT = new URL('..', import.meta.url).pathname;
const OUT = `${ROOT}public/img/`;
const ICONS = `${ROOT}public/icons/`;

/** Widths follow the rendered sizes on the site at 1x and 2x, capped at the source width. */
const SOURCES = {
  'stock/glass': { file: 'stock/glass.jpg', widths: [480, 640, 828, 1080, 1280, 1600] },
  'stock/hero': { file: 'stock/hero.jpg', widths: [400, 640, 828, 1080, 1440] },
  'stock/control': { file: 'stock/control.jpg', widths: [320, 480, 640, 828, 1080, 1280, 1600, 1800] },
  'stock/treasury': { file: 'stock/treasury.jpg', widths: [320, 480, 640, 828, 1080, 1280, 1600, 1800] },
  'stock/privacy': { file: 'stock/privacy.jpg', widths: [320, 480, 640, 828, 1080, 1280, 1600, 1800] },
  'stock/columns': { file: 'stock/columns.jpg', widths: [320, 480, 640, 828] },
  'stock/structure': { file: 'stock/structure.jpg', widths: [320, 480, 640, 828] },
  'brand/logo': { file: 'brand/logo.png', widths: [96, 192, 384, 768] },
  'brand/banner': { file: 'brand/banner.png', widths: [480, 828, 1080, 1440, 2172] },
};

const ENCODERS = {
  avif: (img) => img.avif({ quality: 60, effort: 6, chromaSubsampling: '4:4:4' }),
  webp: (img) => img.webp({ quality: 82, effort: 6, smartSubsample: true }),
  jpg: (img) => img.jpeg({ quality: 85, mozjpeg: true }),
};

const hash = (buffer) => createHash('sha256').update(buffer).digest('hex').slice(0, 10);

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

const manifest = {};
for (const [key, { file, widths }] of Object.entries(SOURCES)) {
  const input = `${ROOT}public/${file}`;
  const { width, height } = await sharp(input).metadata();
  const entry = { width, height };
  for (const [ext, encode] of Object.entries(ENCODERS)) {
    const set = [];
    for (const w of widths.filter((candidate) => candidate <= width)) {
      const buffer = await encode(sharp(input).resize({ width: w, kernel: 'lanczos3' })).toBuffer();
      const name = `${key.replace('/', '-')}-${w}.${hash(buffer)}.${ext}`;
      writeFileSync(OUT + name, buffer);
      set.push([`/img/${name}`, w]);
    }
    entry[ext] = set;
  }
  manifest[key] = entry;
  console.log(key, width, height);
}

writeFileSync(
  `${ROOT}src/app/_images.ts`,
  `// Generated by scripts/images.mjs. Do not edit by hand.\n\n` +
    `export type ImageSet = readonly (readonly [src: string, width: number])[];\n` +
    `export type ImageEntry = { readonly width: number; readonly height: number; readonly avif: ImageSet; readonly webp: ImageSet; readonly jpg: ImageSet };\n\n` +
    `export const IMAGES = ${JSON.stringify(manifest, null, 2)} as const satisfies Record<string, ImageEntry>;\n\n` +
    `export type ImageKey = keyof typeof IMAGES;\n`,
);

// Icons: the transparent mark for browser tabs, the full-bleed logo tile where the platform
// draws its own mask or expects an opaque square.
rmSync(ICONS, { recursive: true, force: true });
mkdirSync(ICONS, { recursive: true });
const mark = `${ROOT}public/brand/mark.png`;
const tile = `${ROOT}public/brand/logo.png`;
for (const size of [16, 32, 48]) {
  await sharp(mark).resize(size, size, { kernel: 'lanczos3' }).png({ compressionLevel: 9 }).toFile(`${ICONS}favicon-${size}.png`);
}
await sharp(tile).resize(180, 180).png({ compressionLevel: 9 }).toFile(`${ICONS}apple-touch-icon.png`);
for (const size of [192, 512]) {
  await sharp(tile).resize(size, size).png({ compressionLevel: 9 }).toFile(`${ICONS}icon-${size}.png`);
}
console.log('icons', readdirSync(ICONS).join(' '));
